---
- name: download jenkins image
  hosts: hosts
  remote_user: vagrant
  become: yes

  tasks:
    - name: update repo
      apt: update_cache=yes

    - name: Run jenkins
      docker_container: 
        name: jenkinscontainer
        image: jenkins/jenkins
        ports: 
         - 9900:8080