---
- name: download nexus image
  hosts: all
  remote_user: vagrant
  become: yes

  tasks:
    - name: update repo
      apt: update_cache=yes
 
    - name: Run nexus
      docker_container: 
        name: nexuscontainer
        image: sonatype/nexus
        ports: 
         - 9901:8081