---
- name: download Docker
  hosts: all
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: update repo
    apt: update_cache=yes
  
  - name: install dependencies
    apt: name={{item}} state=present
    with_items:
    - curl
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python-pip
  
  - name: Add CPG key
    shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

  - name: add Docker repo
    shell: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'

  - name: update repo
    apt: update_cache=yes
    
  - name: install docker
    apt: name=docker-ce state=present

  - name: install docker-py
    shell: pip install docker-py

